#Creating these things for the sake of convenience
TOTAL_FEMALE<-sum(NUMBERS_FEMALE)
TOTAL_TERR<-sum(NUMBERS_MALE[1:2])
TOTAL_SNEAK<-NUMBERS_MALE[3]
#Do survival
NUMBERS_MALE[1:2]<-rmultinom(1,rnorm(1,K1_mean,K1_STD),c(NUMBERS_MALE[1]/TOTAL_TERR,NUMBERS_MALE[2]/TOTAL_TERR))
NUMBERS_FEMSNEAK<-rmultinom(1,rnorm(1,K2_mean,K2_STD),c((TOTAL_SNEAK/(TOTAL_FEMALE+TOTAL_SNEAK)),(NUMBERS_FEMALE[1]/(TOTAL_FEMALE+TOTAL_SNEAK)),(NUMBERS_FEMALE[2]/(TOTAL_FEMALE+TOTAL_SNEAK)),(NUMBERS_FEMALE[3]/(TOTAL_FEMALE+TOTAL_SNEAK))))
NUMBERS_MALE[3]<-NUMBERS_FEMSNEAK[1]
NUMBERS_FEMALE<-NUMBERS_FEMSNEAK[2:4]